import '@radix-ui/themes/styles.css';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Theme, ThemePanel } from '@radix-ui/themes';
import NavBar from './NavBar';
import ReactQueryClientProvider from '@/app/components/ReactQueryClientProvider';
import SessionProvider from '@/app/components/SessionProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <SessionProvider>
      <ReactQueryClientProvider>
        <html lang="en">
          <body className={inter.className}>
            <Theme
              appearance="light"
              accentColor="green"
              panelBackground="solid"
              radius="large"
            >
              <NavBar />
              <main className="p-5">{children}</main>
              {/*<ThemePanel />*/}
            </Theme>
          </body>
        </html>
      </ReactQueryClientProvider>
    </SessionProvider>
  );
}
